version: '3.1'

services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: liferaytest

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9600:9600
      - 9700:9700
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

volumes:
  pgdata:
  esdata:
